Set LSTM __setstate__ to fix broken LSTM in ./tools/play.py (#2124)
I think the newly refactored LSTM is broken with ./tools/play.py. Can
you take a look and see if you agree? I wasn't sure what to fix.

I noticed something weird where when we run `./tools/play.py` it seems
like LSTM state is broken.

I put together a hacky-fix but maybe we can think better about how this
happens and whether we should do something different?

Basically the bug was that the ./tools/play.py LSTM batch size didn't
match what happens when training because of num_workers potentially
being different. And then because of this shapes didn't match up.

```
  File "/Users/relh/Code/workspace/metta/agent/src/metta/agent/lib/metta_layer.py", line 108, in forward
    source.forward(td)
  File "/Users/relh/Code/workspace/metta/agent/src/metta/agent/lib/metta_layer.py", line 110, in forward
    self._forward(td)
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 929, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/relh/Code/workspace/metta/agent/src/metta/agent/lib/lstm.py", line 130, in _forward
    hidden, (h_n, c_n) = self._net(hidden, (h_0, c_0))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 1120, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 1003, in check_forward_args
    self.check_hidden_size(
  File "/Users/relh/Code/workspace/metta/.venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 348, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, list(hx.size())))
RuntimeError: Expected hidden[0] size (2, 24, 128), got [2, 128, 128]
```

[Asana
Task](https://app.asana.com/1/1209016784099267/project/1210348820405981/task/1211060859130897)