shared memory map cache was key-erroring, this no longer does (#4191)
```
Traceback (most recent call last):
  File "/root/.local/share/uv/python/cpython-3.12.11-linux-x86_64-gnu/lib/python3.12/multiprocessing/resource_tracker.py", line 264, in main
    cache[rtype].remove(name)
KeyError: '/mab34df26c91319db_49'
```