Fix core.py (#3605)
I needed these changes to be able to run, for example:

```
uv run ./tools/run.py experiments.recipes.cvc.single_mission.train \
    run=collect_classic_test \
    mission_name=collect_resources_classic \
    num_cogs=4 \
    trainer.total_timesteps=10_000_000
    evaluator.epoch_interval=0
   ```

[Asana Task](https://app.asana.com/1/1209016784099267/project/1210348820405981/task/1211869810981426)

And to fix this error in training:

```
TypeError: _SingleAgentAdapter.reset() got an unexpected keyword
argument
                           'simulation'  
```

Still getting this error in training, during evaluation, due to the observation format in _SingleAgentAdapter._obs_to_td() 
```     
IndexError: Dimension out of range (expected to be in range of [-1, 0],
but got
1)
[NOTE] Failed while executing module 'obs_shim_tokens'.
```        

So please run with  evaluator.epoch_interval=0 for now