fix: troubleshoot CI timeout (#1450)
The app_backend tests are timing out at 10 min.

```
Running tests for app_backend...
Cannot read termcap database;
using dumb terminal settings.
Cannot read termcap database;
using dumb terminal settings.
Cannot read termcap database;
using dumb terminal settings.
bringing up nodes...
bringing up nodes...

Error: The operation was canceled.
```

This PR increases the allowed time to 15 minutes and switches the test
from quiet (-q) to verbose (-v) so that we can troubleshoot what is
going on.

[Asana
Task](https://app.asana.com/1/1209016784099267/project/1210348820405981/task/1210778535720822)